-- Testing is 5 litres PER NOZZLE, not a flat figure per fuel (client 2026-09-14).
--
-- "every pump they take, five liters will be extracted from each side of the
--  pump, and so that is twenty liters, and that is mandatory... if the pump is
--  broken, they don't do the testing."
--
-- Two pumps, two nozzles each, 5 litres a nozzle = 20 litres a day = 10 per
-- fuel. One pump in the workshop is 5 per fuel. The deduction was never a
-- constant; it follows how many pumps ran, and migration 0026's `pump_status`
-- column is what finally records that.
--
-- Sales Man Off is TESTED. Client, same day: "if there is no salesman and the
-- pump works, they'll submit it, because they do the testing and there will be a
-- reading change." Only 'repair' is excused.
--
-- The engine now computes
--
--     deduction per fuel = testing_litres_per_nozzle x (pumps not in repair)
--
-- falling back to the old flat parameter only for a day with no Daily Sales
-- Entry at all, so nothing already closed shifts underneath anyone.
--
-- The derivation reproduces BOTH regimes the station has actually used, which is
-- the strongest evidence it is right:
--
--     2 pumps x 5 = 10   matches the seeded 10.0 and the ledger to 06 Sep
--     1 pump  x 5 =  5   matches migration 0024's 5 and the ledger from 07 Sep
--
-- Effective 2026-08-01, back to the seed's own date, precisely BECAUSE it
-- reproduces the old figures - a day with both pumps running computes 10 either
-- way, so no closed day moves.

INSERT INTO system_parameter (name, value, effective_date, updated_by)
VALUES ('testing_litres_per_nozzle', 5, '2026-08-01', 'client-confirmed-2026-09-14');
